name: 'Setup'
description: 'Common setup steps for Actions'

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v1
      name: Install bun

    - uses: actions/cache@v4
      name: Setup bun cache
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.bun }}-bun-

    - name: Install D2
      shell: bash
      run: curl -fsSL https://d2lang.com/install.sh | sh -s --

    - name: Install dependencies
      shell: bash
      run: bun install

    - name: Build Packages
      shell: bash
      run: bun install

    - name: Install Playwright Browsers
      shell: bash
      run: bun playwright install --with-deps
