$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
ignorePaths:
  - .git
  - bun.lockb
  - ./branch_out
  - .changeset
  - "**/*.generated.*"
  - "**/*.svg"
  - "**/.env"
  - "**/.env.local"
  - "**/.env.production"
  - "**/.env.development"
  - "**/.env.testing"
words:
  - abcdefghjkmnpqrstvwxyz
  - acst
  - aest
  - akst
  - ampffbr
  - Anson
  - apidevtools
  - appkey
  - arktype
  - asteasolutions
  - astro
  - astrojs
  - autodocs
  - autoincrement
  - autoplay
  - Avenir
  - awst
  - Beamer
  - Behaviour
  - bikeshed
  - BIKESHEDDING
  - Binni
  - Blomberg
  - Borla
  - branchname
  - bunx
  - bvaughn
  - Byrom
  - callees
  - citty
  - cjsx
  - classname
  - clsx
  - cmdk
  - CNCF
  - codegen
  - codespace
  - codespaces
  - colinhacks
  - Colm
  - commitlint
  - commitlintrc
  - compat
  - consola
  - consts
  - Croll
  - crossorigin
  - ctsx
  - customizability
  - dagre
  - Daniele
  - datadive
  - datetime
  - dbaeumer
  - degit
  - Deno
  - dflt
  - Diátaxis
  - Dodds
  - Dorfmeister
  - dorny
  - dotenv
  - dsznajder
  - Duarte
  - Elsakaan
  - Embla
  - Enumable
  - esbenp
  - eslintcache
  - Fasel
  - frontends
  - gajus
  - grayscale
  - hjkmnp
  - hono
  - honojs
  - hookform
  - hrana
  - htmx
  - Hudak
  - ianvs
  - ilike
  - inclusivity
  - Injecatble
  - injectee
  - Insertable
  - Introspector
  - jiti
  - jscoverage
  - jspm
  - jupyterhub
  - Jupyterlab
  - Kamp
  - kohler
  - Kyselify
  - Kysely
  - Landy
  - Ledesma
  - Levenberg
  - Libsql
  - Linsley
  - lockb
  - Luca
  - lucaschultz
  - lucide
  - Malyavko
  - Martius
  - microbundle
  - mikestead
  - minimise
  - Mintlify
  - mjsx
  - monorepoing
  - mtsx
  - mysticatea
  - Nault
  - nbformat
  - neonctl
  - neondatabase
  - neverthrow
  - nextjs
  - njsproj
  - nocheck
  - NOTADB
  - notnull
  - Nteifeh
  - nuxt
  - nzst
  - Octoverse
  - onwarn
  - openapi
  - optimisations
  - Ornella
  - oslojs
  - packagejson
  - pacocoursey
  - pagefind
  - pageview
  - peduarte
  - pids
  - Pluggable
  - Pocock
  - posthog
  - Potvin
  - preprocessors
  - Procida
  - qualtrics
  - quickstart
  - Ratelimit
  - rehype
  - rgba
  - Rheinische
  - ROWID
  - Rüeger
  - Runtimes
  - shadcn
  - Sina
  - SPSS
  - sslmode
  - STACKOVERFLOW
  - starterkit
  - starterkits
  - STATA
  - stateofjs
  - stringifying
  - styleguide
  - stylelint
  - stylelintcache
  - stylesheet
  - superjson
  - supermacro
  - swavgqy
  - tada
  - tailwindcss
  - tamasfe
  - tanstack
  - thequickbrownfox
  - thollander
  - todos
  - toolset
  - topbar
  - transpiles
  - transpiling
  - treeshake
  - trpc
  - tsbuildinfo
  - tsconfigs
  - tseslint
  - tsguide
  - TSTRUCT
  - tsup
  - Tuite
  - turborepo
  - TURSO
  - tursodatabase
  - typebox
  - typecheck
  - typegen
  - Typeguard
  - typeof
  - typesafe
  - typespec
  - unifiedjs
  - Universität
  - unkey
  - Updateable
  - uploadthing
  - vaul
  - viewports
  - vite
  - VITEST
  - vuepress
  - WEBASSEMBLY
  - Wickham
  - Wilhelms
  - WITA
  - withastro
  - wscript
  - yoav
