packages: {
  "@datadive/core"
  "@datadive/auth" -> "@datadive/core"
  "@datadive/db" -> "@datadive/core"
  "@datadive/utils" -> "@datadive/core"

  "@datadive/core"
  "@datadive/auth" -> "@datadive/core"
  "@datadive/db" -> "@datadive/core"
  "@datadive/utils" -> "@datadive/core"

  "@datadive/auth"
  "@datadive/db" -> "@datadive/auth"
  "@datadive/utils" -> "@datadive/auth"

  "@datadive/turso"
  "@datadive/utils" -> "@datadive/turso"

  "@datadive/spec"
  "@datadive/utils" -> "@datadive/spec"

  "@datadive/utils"

  "@datadive/db"
  "@datadive/turso" -> "@datadive/db"
  "@datadive/utils" -> "@datadive/db"

  "@datadive/email"
  "@datadive/utils" -> "@datadive/email"
}

apps: {
  "@datadive/docs"

  "@datadive/api"

  "@datadive/web"
}

packages."@datadive/spec" -> apps."@datadive/docs"

packages."@datadive/spec" -> apps."@datadive/web"

packages."@datadive/auth" -> apps."@datadive/api"
packages."@datadive/core" -> apps."@datadive/api"
packages."@datadive/db" -> apps."@datadive/api"
packages."@datadive/spec" -> apps."@datadive/api"
packages."@datadive/turso" -> apps."@datadive/api"
packages."@datadive/utils" -> apps."@datadive/api"
packages."@datadive/email" -> apps."@datadive/api"
