user: User {
  shape: circle
}

frontend: Browser {
  jupyterLab: JupyterLab
}

backend: Server {
  server: Jupyter Server
  file: Notebook File
  kernel: Kernel

  server -> kernel: Code cells
  server <- kernel: Execution results
  server <-> file: Notebook data
}

frontend.jupyterLab <-> user
frontend.jupyterLab <-> backend.server: HTTP API